services:
  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
      target: dev
    volumes:
      - ./:/app
    environment:
      APP_ENV: dev
    networks:
      - poc-network
    depends_on:
      mysql:
        condition: service_healthy

  php-swoole:
    build:
      context: .
      dockerfile: docker/swoole/Dockerfile
      target: dev
    volumes:
      - ./:/app
    environment:
      APP_ENV: dev
      APP_RUNTIME: "Runtime\\Swoole\\Runtime"
      SWOOLE_HOST: "0.0.0.0"
      SWOOLE_PORT: "8000"
    networks:
      - poc-network
    depends_on:
      mysql:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - poc-network
    depends_on:
      - php-fpm
      - php-swoole

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: benchmark
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    restart: always
    volumes:
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    networks:
      - poc-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5

  wrk:
    container_name: "benchmark"
    build:
      context: .
      dockerfile: docker/wrk/Dockerfile
    restart: no
    networks:
      - poc-network
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://web/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  poc-network:
    driver: bridge
